---
- name: 'PostgreSQL-PostGIS Playbook'
  hosts: postgresql_servers

  roles:
    - postgresql
    - postgis
    - pgbouncer

- name: 'D-PLACE Playbook'
  hosts: dplace_servers
  roles:
    - dplace_server
