---
# Will need to convert to ssh and key pair auth
- name: Clone D-PLACE repo
  git: repo={{ dplace.repo }}
       dest="/home/{{ dplace.user }}/{{ dplace.src_dir }}"
  
- name: Install python dependencies in virtualenv
  pip: requirements="/home/{{ dplace.user }}/{{ dplace.src_dir }}/requirements.txt"
       virtualenv="/home/{{ dplace.user }}/{{ dplace.env_dir }}"

# Still todo:
## Edit settings.py / settings.template
## createdb in postgres
## django_manage syncdb
## django_manage migrate
