---
# Will need to convert to ssh and key pair auth
- name: Clone D-PLACE repo
  git: repo={{ dplace.repo }}
       dest="/home/{{ dplace.user }}/{{ dplace.src_dir }}"
  sudo: yes
  sudo_user: "{{ dplace.user }}"
  
- name: Install python dependencies in virtualenv
  pip: requirements="/home/{{ dplace.user }}/{{ dplace.src_dir }}/requirements.txt"
       virtualenv="/home/{{ dplace.user }}/{{ dplace.env_dir }}"
  sudo: yes
  sudo_user: "{{ dplace.user }}"

# Still todo:
- name: Configure DPLACE settings.py for DB
  template: src=settings.py.j2 dest="/home/{{ dplace.user }}/{{ dplace.src_dir }}/dplace/settings.py"
  sudo: yes
  sudo_user: "{{ dplace.user }}"

- name: Synchronize django db
  django_manage: app_path="/home/{{ dplace.user }}/{{ dplace.src_dir }}" command=syncdb virtualenv="/home/{{ dplace.user }}/{{ dplace.env_dir }}"

## django_manage migrate
