---
# Will need to convert to ssh and key pair auth
- name: Clone D-PLACE repo
  git: repo={{ dplace.repo }}
       dest={{ dplace.install_path }}
  sudo: yes
  sudo_user: "{{ dplace.user }}"
  
- name: Install python dependencies in virtualenv
  pip: requirements="{{ dplace.install_path }}/requirements.txt"
       virtualenv="/home/{{ dplace.user }}/{{ dplace.env_dir }}"
  sudo: yes
  sudo_user: "{{ dplace.user }}"

- name: Configure DPLACE settings.py for DB
  template: src=settings.py.j2 dest="{{ dplace.install_path }}/dplace/settings.py"
  sudo: yes
  sudo_user: "{{ dplace.user }}"

- name: Synchronize django db
  django_manage: app_path="{{ dplace.install_path }}" command=syncdb virtualenv="/home/{{ dplace.user }}/{{ dplace.env_dir }}"
  sudo: yes
  sudo_user: "{{ dplace.user }}"

# After syncdb, column width of auth_permission.name is only 50 chars
# With our verbose names, we will exceed 50, so raise the limit before loading data.
# Must be done after tables created but before migration.
#
# See https://code.djangoproject.com/ticket/8162#comment:18
#
- name: Fix column width for auth_permission.name
  shell: "psql {{ dplace.db_name }} -c \"alter table auth_permission alter column name type character varying(100);\""
  sudo: yes
  sudo_user: dplace_user

- name: Run django db migrations with south
  django_manage: app_path="{{ dplace.install_path }}" command=migrate virtualenv="/home/{{ dplace.user }}/{{ dplace.env_dir }}"
  sudo: yes
  sudo_user: "{{ dplace.user }}"
