# This should happen on the database server
# via https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml

---
# Superuser is required to create extension.
- name: Create Postgres user for D-PLACE
  postgresql_user: name={{ dplace.db_user }} role_attr_flags=SUPERUSER,CREATEDB password={{ dplace.db_password }}
  sudo: yes
  sudo_user: postgres

- name: Create Postgres database for D-PLACE
  postgresql_db: name={{ dplace.db_name }} login_user={{ dplace.db_user }} login_password={{ dplace.db_password }} encoding={{ postgresql.encoding }} lc_ctype='{{ postgresql.locale }}.{{ postgresql.encoding }}' lc_collate='{{ postgresql.locale }}.{{ postgresql.encoding }}'
  sudo: yes
  sudo_user: dplace_user

- name: Activate PostGIS extensions on dplace_db
  shell: "psql {{ dplace.db_name }} -c \"CREATE EXTENSION IF NOT EXISTS postgis;CREATE EXTENSION IF NOT EXISTS postgis_topology;\""
  sudo: yes
  sudo_user: dplace_user
