# This should happen on the database server
# via https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml

---
- name: Create Postgres database for D-PLACE
  postgresql_db: name={{ dplace.db_name }}
  sudo: yes
  sudo_user: postgres

- name: create the postgresql user for application
  postgresql_user: name={{ dplace.db_user }}
  sudo: yes
  sudo_user: postgres

- name: Set privileges
  postgresql_user: name={{ dplace.db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: yes
  sudo_user: postgres
  
- name: Activate PostGIS extensions on dplace_db
  shell: "psql {{ dplace.db_name }} -c \"CREATE EXTENSION IF NOT EXISTS postgis;CREATE EXTENSION IF NOT EXISTS postgis_topology;\""
  sudo: yes
  sudo_user: postgres
